//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsSqlDependancyBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsSqlDependancyBrowser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select from where order group by insert update delete merge into having exec with declare create function procedure return returns begin end as if while for set try catch drop table view union all case then when cross apply outerinner left join and or on else raiserror throw tran commit rollback pivot unpivot for cursor open is in not null over partition using values.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM (
        ///    SELECT DISTINCT A.referenced_entity_name, B.type_desc
        ///    FROM sys.dm_sql_referenced_entities(@objectFullName, &apos;OBJECT&apos;) A
        ///    LEFT JOIN sys.objects B ON A.referenced_id = B.object_id
        ///    WHERE A.referenced_id IS NOT NULL
        ///    ) A
        ///ORDER BY LEN(A.referenced_entity_name) desc;.
        /// </summary>
        internal static string queryObjectDependancies {
            get {
                return ResourceManager.GetString("queryObjectDependancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sp_text = B.definition,
        ///       sp_full_name = C.name + &apos;.&apos; + A.name,
        ///	   A.type_desc
        ///FROM sys.objects A
        /// LEFT JOIN sys.sql_modules B ON A.object_id = B.object_id
        ///INNER JOIN sys.schemas C ON A.schema_id = C.schema_id
        ///WHERE A.name = @objectName;.
        /// </summary>
        internal static string queryObjectInfo {
            get {
                return ResourceManager.GetString("queryObjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  [column].name AS &apos;@columnName&apos;,
        ///		[type].name AS &apos;@typeName&apos;, 
        ///		[type].max_length AS &apos;@maxLength&apos;,
        ///		[type].precision &apos;@precision&apos;
        ///	FROM sys.tables as [table]
        ///	INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id
        ///	INNER JOIN sys.types [type] ON [column].system_type_id = [type].system_type_id
        ///	WHERE [table].name = @objectName
        ///	FOR XML PATH(&apos;column&apos;), ROOT(&apos;table&apos;);.
        /// </summary>
        internal static string queryTableXml {
            get {
                return ResourceManager.GetString("queryTableXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;  
        ///    &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;table border=&quot;1&quot;&gt;
        ///        &lt;tr&gt;
        ///          &lt;th&gt;Column Name&lt;/th&gt;
        ///          &lt;th&gt;Type Name&lt;/th&gt;
        ///          &lt;th&gt;Max Length&lt;/th&gt;
        ///          &lt;th&gt;Precision&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///      &lt;xsl:for-each select=&quot;table/column&quot;&gt;
        ///        &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string table2html {
            get {
                return ResourceManager.GetString("table2html", resourceCulture);
            }
        }
    }
}
