//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsSqlDependencyBrowser {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsSqlDependencyBrowser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Source={0};Initial Catalog={1};Integrated Security=True.
        /// </summary>
        internal static string connectionStringTemplate {
            get {
                return ResourceManager.GetString("connectionStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;html ng-app=&quot;MsSqlDependencyBrowser&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title ng-controller=&quot;HeaderCtrl&quot;&gt;{{objectName}}&lt;/title&gt;
        ///    &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-route.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-cookies.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;main.css&quot;&gt;
        ///&lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div id=&quot;params&quot; ng- [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select from where order group by insert update delete merge into having exec with declare create function procedure return returns begin end as if while for set try catch drop table view union all case then when cross apply outer inner left join and or on else raiserror throw tran commit rollback pivot unpivot for cursor open is in not null over partition using values varchar integer int data datetime bit numeric execute fetch nvarchar revert nocount exists uniqueidentifier output.
        /// </summary>
        internal static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на body
        ///{
        ///    overflow: hidden;
        ///    margin-right: 0;
        ///    margin-bottom: 0;
        ///}
        ///
        ///#params {
        ///    width: 100%;
        ///    height: 35px;
        ///    white-space: nowrap;
        ///}
        ///
        ///#objectNavigator {
        ///    width: 15%;
        ///    height: calc(100% - 35px);
        ///    white-space: nowrap;
        ///    float: left;
        ///    outline: 1px solid;
        ///    box-sizing: border-box;
        ///}
        ///
        ///#objectTypeComboBox, #objFilter {
        ///    width: 95%;
        ///    float: left;
        ///    margin-left: 3px;
        ///    margin-right: 3px;
        ///    box-sizing: border-box;
        ///}
        ///
        ///#objectNavigator label {
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string main_css {
            get {
                return ResourceManager.GetString("main_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на obj.
        /// </summary>
        internal static string objectNameParam {
            get {
                return ResourceManager.GetString("objectNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;pre id=&apos;text&apos; ng-bind-html=&apos;objectText&apos;&gt;&lt;/pre&gt;.
        /// </summary>
        internal static string objectText_html {
            get {
                return ResourceManager.GetString("objectText_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на function openModal() {
        ///    var overlay = document.getElementById(&apos;overlay&apos;);
        ///    overlay.classList.remove(&quot;is-hidden&quot;);
        ///}
        ///
        ///function closeModal() {
        ///    var overlay = document.getElementById(&apos;overlay&apos;);
        ///    overlay.classList.add(&quot;is-hidden&quot;);
        ///}
        ///
        ///function selectAllText(containerid) {
        ///    var range;
        ///    if (document.selection) {
        ///        range = document.body.createTextRange();
        ///        range.moveToElementText(document.getElementById(containerid));
        ///        range.select().createTextRange();
        ///    } e [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string postConnectionString_js {
            get {
                return ResourceManager.GetString("postConnectionString_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select A.type_desc, A.name, schema_name = B.name
        ///  from sys.objects A
        ///  left join sys.schemas B on A.schema_id = B.schema_id
        /// where type in (&apos;P&apos;)
        /// order by type_desc, name;
        ///
        ///select A.type_desc, A.name, schema_name = B.name
        ///  from sys.objects A
        ///  left join sys.schemas B on A.schema_id = B.schema_id
        /// where type in (&apos;TF&apos;)
        /// order by type_desc, name;
        ///
        ///select A.type_desc, A.name, schema_name = B.name
        ///  from sys.objects A
        ///  left join sys.schemas B on A.schema_id = B.schema_id
        /// where type in (&apos;IF&apos;)
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string queryAllObjects_sql {
            get {
                return ResourceManager.GetString("queryAllObjects_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select name 
        ///  from sys.databases 
        /// order by name.
        /// </summary>
        internal static string queryDatabaseList_sql {
            get {
                return ResourceManager.GetString("queryDatabaseList_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * 
        ///FROM (
        ///    SELECT DISTINCT 
        ///	       A.referenced_entity_name,
        ///		   B.type_desc,
        ///		   C.base_object_name,
        ///		   D.name AS schema_name
        ///    FROM sys.dm_sql_referenced_entities(@objectFullName, &apos;OBJECT&apos;) A
        ///    LEFT JOIN sys.objects B ON A.referenced_id = B.object_id
        ///	LEFT JOIN sys.synonyms C ON B.object_id = C.object_id
        ///   INNER JOIN sys.schemas D on isnull(B.schema_id, C.schema_id) = D.schema_id
        ///   WHERE A.referenced_id IS NOT NULL
        ///    ) A
        ///ORDER BY LEN(A.referenced_entity_name) desc;.
        /// </summary>
        internal static string queryObjectDependancies_sql {
            get {
                return ResourceManager.GetString("queryObjectDependancies_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT sp_text = B.definition,
        ///       sp_name = C.name,
        ///	   sp_schema = A.name,
        ///	   A.type_desc
        ///FROM sys.objects A
        /// LEFT JOIN sys.sql_modules B ON A.object_id = B.object_id
        ///INNER JOIN sys.schemas C ON A.schema_id = C.schema_id
        ///WHERE A.name = @objectName
        ///  AND C.name = @schemaName;.
        /// </summary>
        internal static string queryObjectInfo_sql {
            get {
                return ResourceManager.GetString("queryObjectInfo_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT  [column].name AS &apos;@columnName&apos;,
        ///		[type].name AS &apos;@typeName&apos;, 
        ///		[type].max_length AS &apos;@maxLength&apos;,
        ///		[type].precision AS &apos;@precision&apos;,
        ///		case [column].is_nullable when 1 then &apos;Yes&apos; when 0 then &apos;No&apos; end AS &apos;@is_nullable&apos;,
        ///		case [column].is_identity when 1 then &apos;Yes&apos; when 0 then &apos;No&apos; end AS &apos;@is_identity&apos;
        ///	FROM sys.tables [table]
        ///	INNER JOIN sys.columns [column] ON [table].object_id = [column].object_id
        ///	INNER JOIN sys.types [type] ON [column].system_type_id = [type].system_type_id
        ///	INNER J [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string queryTableXml_sql {
            get {
                return ResourceManager.GetString("queryTableXml_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sch.
        /// </summary>
        internal static string schemaNameParam {
            get {
                return ResourceManager.GetString("schemaNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;  
        ///    &lt;xsl:template match=&quot;/&quot;&gt;
        ///      &lt;table&gt;
        ///        &lt;tr&gt;
        ///          &lt;th&gt;Column Name&lt;/th&gt;
        ///          &lt;th&gt;Type Name&lt;/th&gt;
        ///          &lt;th&gt;Max Length&lt;/th&gt;
        ///          &lt;th&gt;Precision&lt;/th&gt;
        ///          &lt;th&gt;Is nullable&lt;/th&gt;
        ///          &lt;th&gt;Is identity&lt;/th&gt;
        ///        &lt;/tr&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string table2html_xslt {
            get {
                return ResourceManager.GetString("table2html_xslt", resourceCulture);
            }
        }
    }
}
